#******************************************************************************
# Role: automated postgres install
# File: tasks/main.yml
#******************************************************************************

# Include the individual tasks files
#******************************************************************************
- import_tasks: "thp.yml"
- import_tasks: "sysctl.yml"
